jicofo {
  xmpp: {
    client: {
      client-proxy: "focus.vpn.example.com"
      xmpp-domain: "vpn.example.com"
      domain: "auth.vpn.example.com"
      username: "focus"
      password: "focus-secret"
    }
    trusted-domains: [ "recorder.vpn.example.com" ]
  }
  bridge: {
    brewery-jid: "JvbBrewery@internal.auth.vpn.example.com"
  }
}
