jicofo {
  xmpp: {
    client: {
      client-proxy: "focus.nyx.kuban-forum.ru"
      xmpp-domain: "nyx.kuban-forum.ru"
      domain: "auth.nyx.kuban-forum.ru"
      username: "focus"
      password: "focus-secret"
    }
    trusted-domains: [ "recorder.nyx.kuban-forum.ru" ]
  }
  bridge: {
    brewery-jid: "JvbBrewery@internal.auth.nyx.kuban-forum.ru"
  }
}
