videobridge {
    apis.xmpp-client.configs {
        shard {
            HOSTNAME=localhost
            DOMAIN=auth.nyx.kuban-forum.ru
            USERNAME=jvb
            PASSWORD=ruj5kSng
            MUC_JIDS="jvbbrewery@internal.auth.nyx.kuban-forum.ru"
            MUC_NICKNAME=702efe40-213d-4051-95ac-030d44f11101
        }
    }
}
ice4j {
    harvest {
        mapping {
            aws {
                enabled=false
            }
            stun {
                addresses=["meet-jit-si-turnrelay.jitsi.net:443"]
            }
        }
    }
}
